In [1]:
import math
import numpy as np
import pandas as pd

In [2]:
class GenerateBatch():
    """A class for loading and transforming data for the lstm model"""

    def __init__(self,df):
        self.dat = df.values
        self.len= self.dat.shape[0]

       
    def GenerateBatch(self, seq_len, batch_size):
        '''Yield a generator of training data from filename on given list of cols split for train/test'''
        i = 0
        while i < (self.len - seq_len):
            x_batch = []
            y_batch = []
            for b in range(batch_size):
                if (i >= (self.len - seq_len)
                    # stop-condition for a smaller final batch if data doesn't divide evenly
                    # or stock index
                    yield np.array(x_batch), np.array(y_batch)
                    i = 0
                x, y = self._next_window(i, seq_len, normalise)
                x_batch.append(x)
                y_batch.append(y)
                i += 1
            yield np.array(x_batch), np.array(y_batch)

    def _next_window(self, i, seq_len, normalise):
        '''Generates the next data window from the given index location i'''
        window = self.data_train[i:i+seq_len]
        x = window[:-1]
        y = window[-1, [0]]
        return x, y

   

SyntaxError: invalid syntax (<ipython-input-2-37344fb7b718>, line 19)

In [3]:
from GenerateBatch import GenerateBatch


In [4]:
import numpy as np
x=np.arange(4000).reshape(4,1000).T

In [5]:
y=x[:,3]

In [6]:
y=y.reshape(-1,1)

In [7]:
stockoffset=[5,12,18,50, 4000]

In [8]:
g=GenerateBatch(x,y,stockoffset)

In [9]:
gb=g.GenerateBatch2(5,3)

###### next 


In [49]:
n=next(gb)

In [50]:
n0=n[0]
n1=n[1]

In [51]:
print(n0.shape[0])
print("y",n1)
for i in range(n0.shape[0]):
    print(i)
    print(n0[i])

3
y [[3054]
 [3055]
 [3056]]
0
[[  50 1050 2050 3050]
 [  51 1051 2051 3051]
 [  52 1052 2052 3052]
 [  53 1053 2053 3053]
 [  54 1054 2054 3054]]
1
[[  51 1051 2051 3051]
 [  52 1052 2052 3052]
 [  53 1053 2053 3053]
 [  54 1054 2054 3054]
 [  55 1055 2055 3055]]
2
[[  52 1052 2052 3052]
 [  53 1053 2053 3053]
 [  54 1054 2054 3054]
 [  55 1055 2055 3055]
 [  56 1056 2056 3056]]
