Test  that GenerateBatch returns batchs of size batch and sequence length seq, where
each sequence is a sliding window over the rows of a numpy array. 


In [1]:
import pandas as pd
import numpy as np
from keras.utils import to_categorical
import os
# work-around to allow import from directory on same level
from GenerateBatch import GenerateBatch

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
np.random.randint(3,size=10)

array([1, 2, 2, 1, 1, 0, 0, 0, 2, 2])

In [3]:
xdat=np.arange(140).reshape(14,10)
print(xdat)
#y=to_categorical(np.random.randint(3,size=np.shape(x)[0]))
ydat=np.arange(42).reshape(14,3)
print(ydat)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]]


In [4]:
seq=2
batch=3
g=GenerateBatch(xdat,ydat)
z=g.GenerateBatch(seq,batch)

In [5]:
i=0
for i in range(2):
    x,y=next(z)
    print('mini_batch %i' %i)
    print('mini batch size %i' %x.shape[0])
    print('sequence length %i ' % x[0].shape[0])
    print('x',x)
    print('y',y)
    print(' ')
    i+=1

mini_batch 0
mini batch size 3
sequence length 2 
x [[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]
y [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 
mini_batch 1
mini batch size 3
sequence length 2 
x [[[30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]]]
y [[12 13 14]
 [15 16 17]
 [18 19 20]]
 


In [6]:
import tensorflow as tf
import numpy as np
dataset = tf.data.Dataset.from_tensor_slices(np.arange(1000).reshape(100,10))
dataset = dataset.apply(tf.contrib.data.sliding_window_batch(window_size=4))
iterator = dataset.make_one_shot_iterator()
element = iterator.get_next()

with tf.Session() as sess:
    while True:
        try:
            print(sess.run(element))
        except tf.errors.OutOfRangeError:
            print('end')
            break

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]
[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85 

In [7]:
import tensorflow as tf
import numpy as np
dataset1 = tf.data.Dataset.from_tensor_slices(np.arange(100).reshape(10,10))
dataset1 = dataset1.apply(tf.contrib.data.sliding_window_batch(window_size=4))
#
dataset2 = tf.data.Dataset.from_tensor_slices(10*np.arange(100).reshape(10,10))
dataset2 = dataset2.apply(tf.contrib.data.sliding_window_batch(window_size=4))
#
iterator1 = dataset1.make_one_shot_iterator()
iterator2 = dataset2.make_one_shot_iterator()  
#                                            
element1= iterator1.get_next()
element2=  iterator2.get_next() 
#


with tf.Session() as sess:
    while True:
        try:
            print(sess.run([element1,element2]))
        except tf.errors.OutOfRangeError:
            print('end')
            break

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]), array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390]])]
[array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]), array([[100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])]
[array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44,

In [8]:
np.pad(np.arange(10),(5,5),'constant')

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0])

In [9]:
#https://stackoverflow.com/questions/41879440/how-to-implement-a-sliding-window-in-tensorflow
# NOTE: If you call this function often, you may want to (i) move the `np.pad()`
# into the graph as `tf.pad()`, and (ii) replace `X_t` with a placeholder.
sess=tf.Session()
window_size=5
X=np.arange(1000).reshape(10,100)
seqs=X.shape[-1]-window_size
X_t  = tf.constant(X,dtype=tf.float32)

def window_func(start):
    end = start + window_size
    X_matrix = tf.reshape(X_t[:,start:end],(-1,window_size))
    return X_matrix
    

output_t = tf.map_fn(window_func, tf.range(seqs),dtype=tf.float32)

output = sess.run(output_t)

In [10]:
output.shape

(95, 10, 5)

In [11]:
output[0].shape

(10, 5)

In [12]:
output[0]


array([[  0.,   1.,   2.,   3.,   4.],
       [100., 101., 102., 103., 104.],
       [200., 201., 202., 203., 204.],
       [300., 301., 302., 303., 304.],
       [400., 401., 402., 403., 404.],
       [500., 501., 502., 503., 504.],
       [600., 601., 602., 603., 604.],
       [700., 701., 702., 703., 704.],
       [800., 801., 802., 803., 804.],
       [900., 901., 902., 903., 904.]], dtype=float32)

In [13]:
output.shape

(95, 10, 5)

In [19]:
import tensorflow as tf
import numpy as np
dataset1 = tf.data.Dataset.from_tensor_slices(np.arange(100).reshape(10,10))
dataset2 = tf.data.Dataset.from_tensor_slices(10*np.arange(100).reshape(10,10))
dataset3=tf.data.Dataset.zip((dataset1,dataset2))
#
iterator = dataset3.make_one_shot_iterator()

#                                            
element= iterator.get_next()


with tf.Session() as sess:
    while True:
        try:
            print(sess.run(element))
        except tf.errors.OutOfRangeError:
            print('end')
            break

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))
(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190]))
(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([200, 210, 220, 230, 240, 250, 260, 270, 280, 290]))
(array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]), array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390]))
(array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), array([400, 410, 420, 430, 440, 450, 460, 470, 480, 490]))
(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), array([500, 510, 520, 530, 540, 550, 560, 570, 580, 590]))
(array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]), array([600, 610, 620, 630, 640, 650, 660, 670, 680, 690]))
(array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]), array([700, 710, 720, 730, 740, 750, 760, 770, 780, 790]))
(array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]), array([800, 810, 820, 830, 840, 850, 860, 870, 880, 890]))
(array([90, 91, 92, 93, 94, 95, 96, 97,